version: '3.8'

services:
  streamlit:
    container_name: streamlit_app
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
